### ISSUE TITLE
Error to start project with spring-boot-starter-rollbar

### ISSUE THREAD

**Issue by clakrall** [olmero/rollbar-spring-boot-starter#3] opened 2018-08-02 18:54 UTC
I'm trying configuration the spring-boot-starter-rollbar,  but the error below occurs:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ch.olmero.rollbar.configuration.RollbarAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.rollbar-ch.olmero.rollbar.configuration.RollbarProperties': Could not bind properties to RollbarProperties (prefix=com.rollbar, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is java.lang.NullPointerException
`

My configurations:

Gradle:
```
dependencies {
	compile 'ch.olmero:spring-boot-starter-rollbar:2.0.1.RELEASE'
}

```
Properties file:
```
com.rollbar.access-token=my_key
com.rollbar.environment=default

```

**Comment by marcgs** [comment] 2018-08-08 08:32
I can not reproduce your issue. Is there any more information available in the logs? Or a stack trace? Do you have a repo I can take a look at?

**Comment by pkaufi** [comment] 2018-09-07 13:12
@clakrall can you provide some more context? e.g. what spring-boot version are you using?

**Comment by pkaufi** [comment] 2018-09-20 13:52
closing because no reaction from creator of issue

**Closed by pkaufi** 2018-09-20 13:52 UTC
